version: '3'

services:
  BE_179925:
    image: onistderfalke2/be_179925
    ports:
      - 19925:80
      - 19926:443
    restart: always
    environment:
      PS_INSTALL_AUTO: 0
      PS_ERASE_DB: 0
      DB_HOST: actina15.maas
      DB_USER: BE_179925
      DB_PASSWD: Admin123@
      DB_NAME: BE_179925
      PS_DEV_MODE: 0
      ALLOW_OVERRIDE: 1
    deploy:
      replicas: 1
