<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMshqujl\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMshqujl/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerMshqujl.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerMshqujl\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerMshqujl\appProdProjectContainer([
    'container.build_hash' => 'Mshqujl',
    'container.build_id' => '6b72f133',
    'container.build_time' => 1636099755,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMshqujl');
